#!/bin/sh
arg1=$1
arg2=$2
arg3=$3

rotationcount=20
updateRotationCount() {
  if [ -z $arg2 ]
  then
    rotationCount=20
  else
    rotationCount=$arg2
  fi
}

destroyOldSnap() {
 currentSnapNum=`zfs list -t snapshot | grep $arg1@ | awk 'END{print NR}'`
 while [ $currentSnapNum -ge $rotationCount ]
 do
   destroy=`zfs list -t snapshot | grep $arg1@ | awk -F " " '{if(NR==1)print $1}'`
   zfs destroy -r $destroy
   currentSnapNum=`zfs list -t snapshot | grep $arg1@ | awk 'END{print NR}'`
 done
}

createNewSnap() {
  time=`date +"%Y-%m-%d_%H:%M:%S"`
  zfs snapshot $arg1@$time
}

createZbackup() {
  updateRotationCount
  destroyOldSnap
  createNewSnap
}

checkUsage() {
  #check different usage
  if [ $arg1 = "--list" ]
  then
    listZbackup  
  elif [ $arg1 = "--delete" ]
  then
    deleteZbackup
  elif [ $arg1 = "--export" ]
  then
    exportZbackup
  elif [ $arg1 = "--import" ]
  then
    importZbackup
  else
    createZbackup
  fi
}

if [ -z $arg1 ]
then
  echo "argument 1 is empty"
else
 createZbackup
fi

